#' Example Tree data
#'
#' An example data set of 10,000 trees randomly generated to provide example function for FSMM.
#'
#' @format A data frame with 10,000 rows and 6 columns
#'
#' @param Tree unique tree ID number
#' @param BS binary presence of bark splits
#' @param DBH diameter at breast height, cm
#' @param DB percent crown dieback, 5-100%
#' @param V vigor rating with 1 the healthiest and 5 half of crown dead
#' @param WP binary presence of woodpecker activity
#'
#' @source randomly generated by [fsmm] authors
"tree10000"
