#' Example Tree data
#'
#' An example data set of 10,000 trees randomly generated to provide example function for FSMM.
#'
#' @format
#' A data frame with 10,000 rows and 6 columns
#' \describe{
#'  \item{Tree}{unique tree ID number}
#'  \item{BS}{binary presence of bark splits}
#'  \item{DBH}{diameter at breast height, cm}
#'  \item{DB}{percent crown dieback, 5-100%}
#'  \item{V}{vigor rating with 1 the healthiest and 5 half of crown dead}
#'  \item{WP}{binary presence of woodpecker activity}
#' }
#' @source randomly generated by FSMM authors
"tree10000"
